name: ci

on:
  push:
    branches-ignore: ["ci"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.1.2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C compiler clean
      - run: pnpm -C compiler coverage
      - run: pnpm -C compiler run-p build docs
      - run: pnpm -C editor build
      - if: contains(github.ref, 'main')
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git add -f compiler/dist docs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:ci -f
