name: ci

on:
  push:
    branches-ignore: ["ci"]

concurrency: ci-${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.1.2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C compiler clean
      - run: pnpm -C compiler/test exec tsc #typecheck tests
      - run: pnpm -C compiler coverage
      - run: pnpm -C compiler build
      - run: pnpm -C website build

      - name: Deploy
        if: contains(github.ref, 'main')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ci
          folder: website/docs/.vitepress/dist
          target-folder: docs
          clean-exclude: pr-preview/
          force: false
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
