name: Lint

on:
  push:
    branches-ignore: ["ci"]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C compiler lint
