name: pr

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.14.1
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C compiler clean
      - run: pnpm -C compiler/test exec tsc #typecheck tests
      - run: pnpm -C compiler coverage
      - run: pnpm -C compiler build
      - run: pnpm -C website build
