name: pr

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C compiler clean
      - run: pnpm -C compiler coverage
      - run: pnpm -C compiler run-p build docs
      - run: pnpm -C editor build
