name: pr

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --immutable
      - run: yarn workspace mlogjs clean
      - run: yarn workspace mlogjs coverage
      - run: yarn workspace mlogjs run-p build docs
      - run: yarn workspace editor build
